### ISSUE TITLE
Thin black outline around text

### ISSUE THREAD

**Issue by jowie** [MuscleRumble/THLabel#26]
If I render a white THLabel above a white background, you can see it adding a thin black line around the text. This also means that text rendered small will become thinner and disappear quicker than it should.

![screen shot 2014-10-16 at 10 57 55](https://cloud.githubusercontent.com/assets/176042/4660729/36665152-551b-11e4-9e34-dd1d55fd9720.png)

![screen shot 2014-10-16 at 10 59 47](https://cloud.githubusercontent.com/assets/176042/4660733/3a9739e4-551b-11e4-89ac-9222cde75614.png)

![screen shot 2014-10-16 at 10 58 51](https://cloud.githubusercontent.com/assets/176042/4660740/49aa0f60-551b-11e4-8d7c-01b9018e69a0.png)

**Comment by pronebird** [comment]
@jowie  How do you use it in cocos2d? Why don't you use other more reasonable solutions in OpenGL context, like TTF renderer or pre-rendered bitmap font?

**Comment by jowie** [comment]
Sorry, I haven't been checking my messages. I don't believe I ever said "non-UIKit application"...?

I'm afraid I won't be able to help on this subject much anymore, as I have left the company I was doing the project for. Sorry!

**Comment by MuscleRumble** [comment]
No problem! You said something about "If I run the same code in a UIKit application [...]" and linked to a cocos2d stackoverflow answer. That's why I thought you were talking about a "non-UIKit application".

**Comment by jowie** [comment]
Now it's coming back to me... Sorry it's been a while. Yes, when I said "UIKit Application", I meant an app that wasn't using cocos2d. I'm not entirely sure now why we weren't using a different solution for cocos2d, so I would ignore my ramblings now!

**Comment by MuscleRumble** [comment]
Alright, thanks for the info though! :)
