### ISSUE TITLE
EXC Bad Access on CTFrameSetter

### ISSUE THREAD

**Issue by AmbroiseCollon** [MuscleRumble/THLabel#38]
I installed latest version via cocoa pods.
I target iOS 9.0 and higher.

This lines throws a `EXC_BAD_ACCES` error :
`CTFramesetterRef framesetterRef = CTFramesetterCreateWithAttributedString(attributedStringRef);
`

Any idea why ?

**Comment by MuscleRumble** [comment]
Is there any way to reproduce this error in a minimal project? Have you tried the example project of THLabel? It's hard to say why this error occurs without being able to debug.

**Comment by AmbroiseCollon** [comment]
I think it's linked to IBDesignable. When I removed it, it worked.

**Comment by MuscleRumble** [comment]
Alright! I'll close this for now. Feel free to re-open, if you think it's an actual bug with THLabel that needs to be fixed. :)
